version: '3'
services:
  prometheus: 
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /home/kavya/dockerrepo/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always

  grafana: 
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /home/kavya/dockerrepo:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: always
